- hosts: control
  become: true
  roles:
    - jmeter

- hosts: server
  become: true
  roles:
    - nginx
    - node_exporter

- hosts: monitor
  become: true
  roles:
    - prometheus
    - node_exporter
    - grafana
    - blackbox_exporter
